name: ticktock
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/tacheraSasi/ticktock

environment:
  sdk: ^3.7.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
